#!/usr/bin/env bash
set -e

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

# Idiot proof this shit
if ! [ -d ".git" ]; then
    echo "You must clone the repo instead of downloading it."
    exit
fi

if ! [ -e "/opt/cathook/" ]; then
    echo "Previous Cathook installation not found! Let's install it..."
    cd; git clone https://github.com/cyrexlinuz/cathook
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch --unshallow
    git submodule foreach --recursive 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"'
    git submodule foreach --recursive 'git fetch --unshallow'
    
    # config setup
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    configfile="$DIR/updater-preferences"
    . config.shlib
    cfg_write $configfile update_channel developer
    cfg_write $configfile autoupdater false
    ./install-all
    
    if ! [ -e "/opt/cathook/" ]; then
        echo "Failed to install Cyrex's Cathook fork! You have to do that manually. You can contact me about it."
        exit
    fi
    
    echo "Cathook installation succeded."
fi

if [ -f /usr/bin/apt-get ]; then
    echo "Aptitude detected. Attempting automatic installation of required dependencies..."
    sudo apt-get install curl nodejs firejail net-tools x11-xserver-utils -y
    echo "Installing latest version of NodeJS..." # Ubuntu has NodeJS 8 on their official repos bruh
    curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
    sudo apt-get install nodejs -y
fi

if [ -f /usr/bin/dnf ]; then
    echo "Dandified yum detected. Attempting automatic installation of required dependencies..."
    sudo dnf install curl nodejs firejail net-tools xorg-x11-server-utils -y
fi

if [ -f /usr/bin/pacman ]; then
    echo "Pacman detected. Attempting automatic installation of required dependencies..."
    sudo pacman -Syu curl nodejs npm firejail net-tools xorg-xhost
fi

if [ ! -x "$(command -v touch)" ]; then
    echo "Touch doesn't exist. Please install it. (touch)"
    exit
fi

if [ ! -x "$(command -v route)" ] && [ ! -x /sbin/route ]; then
    echo "Perhaps auto install failed :( Route doesn't exist. Please install it manually. (net-tools)"
    exit
fi

if [ ! -x "$(command -v npm)" ]; then
    echo "Perhaps auto install failed :( NPM doesn't exist. Please install it manually. (npm)"
    exit
fi

if [ ! -x "$(command -v firejail)" ]; then
    echo "Perhaps auto install failed :( Firejail doesn't exist. Please install it manually. (firejail)"
    exit
fi

if [ ! -x "$(command -v pgrep)" ]; then
    echo "Pgrep doesn't exist. Please install it."
    exit
fi

./remove-legacy

if [ ! -d "./cathook" ]; then
    URL="https://github.com/cyrexlinuz/cathook"
    git clone --recursive $URL
fi

if [ -d ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/ ]; then
    if [ -d ./catbot-database ]; then
        echo "Fetching navmeshes..."
        pushd catbot-database
        git fetch --depth 1
        git reset --hard origin/master
        popd
    else
        git clone --depth 1 https://github.com/nullworks/catbot-database
    fi

    echo "Copying navmeshes..."
    rsync catbot-database/nav\ meshes/*.nav ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/
    chmod 755 ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/*.nav # fixup permissions so tf2 is happy
fi

mkdir -p user_instances

if [ ! -f /opt/cathook/bin/libcathook-textmode.so ]; then
    numcpu=$(grep -c ^processor /proc/cpuinfo)
    mkdir -p build
    pushd build
    cmake -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=0 -DEnableOnlineFeatures=0 ../cathook/
    make -j$numcpu
    if ! [ -e "bin/libcathook.so" ]; then
        echo "FATAL: Build failed"
        exit
    fi
    popd
    sudo mkdir -p "/opt/cathook/bin/"
    sudo mkdir -p "/opt/cathook/data/configs"
    sudo cp "build/bin/libcathook.so" "/opt/cathook/bin/libcathook-textmode.so"
    sudo chmod -R 0755 /opt/cathook/data/configs/
fi

if [ ! -d "./just-disable-vac" ]; then
    git clone https://gitlab.com/nullworks/cathook/just-disable-vac
    pushd just-disable-vac
    mkdir -p build && pushd build
    cmake .. && make
    popd; popd
fi

if [ ! -d "./cathook-ipc-server" ]; then
    git clone --recursive https://github.com/nullworks/cathook-ipc-server
    pushd cathook-ipc-server
    ./install.sh
    popd
fi

if [ ! -d "./cathook-ipc-web-panel" ]; then
    git clone --recursive https://github.com/nullworks/cathook-ipc-web-panel
    pushd cathook-ipc-web-panel
    ./update.sh
    popd
fi

if [ ! -d "./cathook-ipc-web-panel/logs" ]; then
    mkdir -p ./cathook-ipc-web-panel/logs
    touch ./cathook-ipc-web-panel/logs/main.log
fi

sudo cp bots.conf /opt/cathook/data/configs/bots.conf
sudo chmod 777 /opt/cathook/data/configs/bots.conf
sudo chown $(whoami):$(whoami) /opt/cathook/data/configs/bots.conf

catconfig=~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/cfg/cat_autoexec_textmode.cfg
if [[ -f "$catconfig" ]]; then
    if grep -Fxq "$catconfig"
    then
        echo "Found Steam directory. Installing bot config..."
        echo "cat_load bots" >> $catconfig
    else
        echo "Found cat_load config inside autoexec! Not going to auto-add it. You might want to add (cat_load bots) inside that file to the very bottom of it."
    fi
else
    echo "Unable to find cathook's autoexec config file. You need to append this line (cat_load bots) yourself inside steam/steamapps/common/Team Fortress 2/tf/cfg/cat_autoexec_textmode.cfg file for IPC bots to work."
fi

sudo sed -i 's/^restricted-network yes/# restricted-network yes/g' /etc/firejail/firejail.config

echo "Installation finished. Please ensure that all navmashes are inside your map folder (see https://github.com/nullworks/catbot-database)."
echo
echo "The web-panel and account storage can be started with ./start"
echo
echo "Now you need to navigate to https://accgen.cathook.club to create accounts."
echo "Create a list of steam accounts from there, and save them to catbot-setup/accounts.txt in username:password format."
